volumes:
  pg-data: {}
  keycloak_data: {}
  traefik-certificates: {}

services:
  proxy:
    image: traefik:v3.0
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--log.level=DEBUG"
    ports:
      - "9480:80"
      - "9443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  casbin-api:
    image: casbinminimalapi
    build:
      context: .
      dockerfile: CasbinMinimalApi/Dockerfile
    env_file:
      - api.env
    depends_on:
      - proxy
      - pgsql
    labels:
      - "traefik.enable=true"
      # Router HTTP
      - "traefik.http.routers.casbin-http.rule=Host(`api.casbin`)"
      - "traefik.http.routers.casbin-http.entrypoints=web"
      - "traefik.http.services.casbin.loadbalancer.server.port=8080"
      # Router HTTPS
      - "traefik.http.routers.casbin-https.rule=Host(`api.casbin`)"
      - "traefik.http.routers.casbin-https.entrypoints=websecure"
      - "traefik.http.routers.casbin-https.tls=true"
      - "traefik.http.services.casbin.loadbalancer.server.port=8080"

  pgsql:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Azerty123!!!
      - POSTGRES_DB=casbin-minimal
    volumes:
      - pg-data:/var/lib/postgresql/data
