services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.0
    command: 
      - "start-dev"
      - "--http-port=8080"
    env_file:
      - kc.env
    volumes:
      - keycloak_data:/opt/keycloak/data
    ports:
      - "8780:8080" 
  
  casbin-api:
    image: casbinminimalapi
    build:
      context: .
      dockerfile: CasbinMinimalApi/Dockerfile
    ports:
      - "8680:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - PG_CONNECTION_STRING=Host=pgsql;Database=casbin-minimal;
      - PGUSER=postgres
      - PGPASSWORD=Azerty123!!!
      - OPENID_CLIENT=scissors-auth-client
      - OPENID_AUTHORITY=http://keycloak:8080/realms/scissors-realm
      - OPENID_SECRET=chtX1m8YPSLos2AD7JSIYo4DHV5F2HCc
    depends_on:
      - pgsql
  
  pgsql:
    image: postgres:17
    ports:
      - "18534:5432" 
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data: { }
  keycloak_data: { }