services:
  casbin-api:
    image: casbinminimalapi
    build:
      context: .
      dockerfile: CasbinMinimalApi/Dockerfile
    ports:
      - "8680:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - PG_CONNECTION_STRING=Host=pgsql;Database=casbin-minimal;
      - PGUSER=postgres
      - PGPASSWORD=Azerty123!!!
    depends_on:
      - pgsql
  
  pgsql:
    image: postgres:17
    env_file:
      - pg.env
    volumes:
        - pg-data:/var/lib/postgresql/data

volumes:
  pg-data: {}