@CasbinMinimalApi_HostAddress = http://localhost:8680

### Identity - Register
POST {{CasbinMinimalApi_HostAddress}}/register
Content-Type: application/json
Accept: application/json

{
	"email": "operator@duckburg.com",
	"password": "Pass123$",
	"confirmPassword": "Pass123$"
}

### Identity - Login
POST {{CasbinMinimalApi_HostAddress}}/login?useCookies=true
Content-Type: application/json
Accept: application/json

{
  "email": "operator@duckburg.com",
  "password": "Pass123$"
}

### Identity - Login
POST {{CasbinMinimalApi_HostAddress}}/login/keycloak
Accept: application/json

