@CasbinMinimalApi_HostAddress = http://localhost:8680

### Identity - Register
POST {{CasbinMinimalApi_HostAddress}}/register
Content-Type: application/json
Accept: application/json

{
	"email": "alice@example.com",
	"password": "Pass123$",
	"confirmPassword": "Pass123$"
}

### Identity - Login
POST {{CasbinMinimalApi_HostAddress}}/login
Content-Type: application/json
Accept: application/json

{
	"email": "alice@example.com",
	"password": "Pass123$"
}

### Identity - Logout (si cookie auth)
POST {{CasbinMinimalApi_HostAddress}}/logout
Accept: application/json

