@CasbinMinimalApi_HostAddress = http://localhost:8680

GET {{CasbinMinimalApi_HostAddress}}/weatherforecast/
Accept: application/json

###

### Casbin Authorization - Check permission
GET {{CasbinMinimalApi_HostAddress}}/casbin/permission/check?User=alice&Resource=data1&Action=read
Accept: application/json

### Casbin Authorization - List roles for user
GET {{CasbinMinimalApi_HostAddress}}/casbin/users/alice/roles
Accept: application/json

### Casbin Authorization - Add role to user
POST {{CasbinMinimalApi_HostAddress}}/casbin/users/alice/roles/admin
Accept: application/json

### Casbin Authorization - Remove role from user
DELETE {{CasbinMinimalApi_HostAddress}}/casbin/users/alice/roles/admin
Accept: application/json

### Casbin Authorization - List users for role
GET {{CasbinMinimalApi_HostAddress}}/casbin/roles/admin/users
Accept: application/json

### Casbin Authorization - Add permission to role
POST {{CasbinMinimalApi_HostAddress}}/casbin/roles/admin/permissions
Content-Type: application/json
Accept: application/json

{
	"Resource": "data1",
	"Action": "read"
}

### Casbin Authorization - Remove permission from role
DELETE {{CasbinMinimalApi_HostAddress}}/casbin/roles/admin/permissions?Resource=data1&Action=read
Accept: application/json