name: Build and Push Docker image

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check DockerHub secrets
        run: |
          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ] || [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "ERROR: DockerHub secrets DOCKERHUB_USERNAME and/or DOCKERHUB_TOKEN are not set."
            echo "Please add them in: Settings → Secrets and variables → Actions for this repository."
            exit 1
          fi

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: CasbinMinimalApi/Dockerfile
          push: true
          tags: |
            tatanecode/casbin-minimal-api:latest
            tatanecode/casbin-minimal-api:${{ github.sha }}
